### ISSUE TITLE
OpenCV contrib mirrors are broken

### ISSUE THREAD

**Issue by amdazm05** [amdazm05/weave#10]
OpenCV contrib mirrors are broken , investigate and fix these to fix main compilation|
Here are the reproducer steps
```
space @ SpaceDandy ~/workspace/weave/build
└─ $ ▶ cmake ..
WEAVE_CMAKE_PROJECT_VERSION : 0.0.0
-- Populating catch2
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/space/workspace/weave/build/_deps/catch2-subbuild
[ 11%] Performing update step for 'catch2-populate'
-- Already at requested tag: v3.6.0
[ 22%] No patch step for 'catch2-populate'
[ 33%] No configure step for 'catch2-populate'
[ 44%] No build step for 'catch2-populate'
[ 55%] No install step for 'catch2-populate'
[ 66%] No test step for 'catch2-populate'
[ 77%] Completed 'catch2-populate'
[100%] Built target catch2-populate
/home/space/workspace/weave/build/_deps/catch2-src
Tests Enabled for WEAVE 0.0.0 
-- Configuring done (2.9s)
-- Generating done (0.1s)
-- Build files have been written to: /home/space/workspace/weave/build
space @ SpaceDandy ~/workspace/weave/build
└─ $ ▶ make
[  5%] Built target OpenSSL
[ 10%] Built target Libcurl
[ 14%] Built target hiredis
[ 18%] Built target spdlog
[ 18%] Performing update step for 'opencv_contrib'
-- Already at requested tag: 4.7.0
[ 19%] No patch step for 'opencv_contrib'
[ 20%] No configure step for 'opencv_contrib'
[ 21%] No build step for 'opencv_contrib'
[ 22%] No install step for 'opencv_contrib'
[ 22%] Completed 'opencv_contrib'
[ 22%] Built target opencv_contrib
[ 22%] Performing download step (git clone) for 'opencv'
Cloning into 'opencv_source'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 726 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'opencv_source'...
```

**Comment by amdazm05** [comment]
@Ubaid-ur-Rahman

**Comment by Ubaid-ur-Rahman** [comment]
Some problem with libcurl

`
[95%] Linking CXX executable 003-libcurl_dep_test
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-version.o): in function `curl_version':
version.c:(.text+0xe6): undefined reference to `zlibVersion'
/usr/bin/ld: version.c:(.text+0x111): undefined reference to `BrotliDecoderVersion'
/usr/bin/ld: version.c:(.text+0x157): undefined reference to `ZSTD_versionNumber'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-version.o): in function `curl_version_info':
version.c:(.text+0x2b6): undefined reference to `zlibVersion'
/usr/bin/ld: version.c:(.text+0x2c2): undefined reference to `BrotliDecoderVersion'
/usr/bin/ld: version.c:(.text+0x2cd): undefined reference to `BrotliDecoderVersion'
/usr/bin/ld: version.c:(.text+0x30f): undefined reference to `ZSTD_versionNumber'
/usr/bin/ld: version.c:(.text+0x31a): undefined reference to `ZSTD_versionNumber'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `zstd_do_close':
content_encoding.c:(.text+0x7c): undefined reference to `ZSTD_freeDStream'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `zstd_do_init':
content_encoding.c:(.text+0x99): undefined reference to `ZSTD_createDStream'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `brotli_do_close':
content_encoding.c:(.text+0xd2): undefined reference to `BrotliDecoderDestroyInstance'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `brotli_do_write':
content_encoding.c:(.text+0x1bb): undefined reference to `BrotliDecoderDecompressStream'
/usr/bin/ld: content_encoding.c:(.text+0x1ee): undefined reference to `BrotliDecoderDestroyInstance'
/usr/bin/ld: content_encoding.c:(.text+0x245): undefined reference to `BrotliDecoderGetErrorCode'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `brotli_do_init':
content_encoding.c:(.text+0x2df): undefined reference to `BrotliDecoderCreateInstance'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `zstd_do_write':
content_encoding.c:(.text+0x466): undefined reference to `ZSTD_decompressStream'
/usr/bin/ld: content_encoding.c:(.text+0x46e): undefined reference to `ZSTD_isError'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `deflate_do_init':
content_encoding.c:(.text+0x5a7): undefined reference to `inflateInit_'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `deflate_do_close':
content_encoding.c:(.text+0x655): undefined reference to `inflateEnd'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `gzip_do_close':
content_encoding.c:(.text+0x6e5): undefined reference to `inflateEnd'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `exit_zlib':
content_encoding.c:(.text+0x77c): undefined reference to `inflateEnd'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `gzip_do_init':
content_encoding.c:(.text+0x809): undefined reference to `zlibVersion'
/usr/bin/ld: content_encoding.c:(.text+0x835): undefined reference to `inflateInit2_'
/usr/bin/ld: content_encoding.c:(.text+0x881): undefined reference to `inflateInit2_'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `inflate_stream':
content_encoding.c:(.text+0x931): undefined reference to `inflate'
/usr/bin/ld: content_encoding.c:(.text+0xab4): undefined reference to `inflateEnd'
/usr/bin/ld: content_encoding.c:(.text+0xacd): undefined reference to `inflateInit2_'
/usr/bin/ld: content_encoding.c:(.text+0xb75): undefined reference to `inflateEnd'
/usr/bin/ld: ../libcurl/lib/libcurl.a(libcurl_la-content_encoding.o): in function `gzip_do_write':
content_encoding.c:(.text+0xfdf): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/003-libcurl_dep_test.dir/build.make:102: tests/003-libcurl_dep_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:1259: tests/CMakeFiles/003-libcurl_dep_test.dir/all] Error 2
make: *** [Makefile:91: all] Error 2 `

**Comment by amdazm05** [comment]
Fixed in [!13](https://github.com/amdazm05/weave/pull/13)
